### ISSUE TITLE
iOS 7 depiction style looks odd

### ISSUE THREAD

**Issue by citrusui** [tmnlsthrn/Lotus#2]
On iOS 7 (most devices), the loutus depiction style looks... "non native".

What do I mean by this? Well, take a look at this first picture of my repo using the current version of lotus (albeit custom).
![image](https://cloud.githubusercontent.com/assets/9056756/7193884/6c294324-e474-11e4-978f-5c9453e14a5d.jpg)

Notice how the "bar" at the top leaves no space for the Author and Change Package Settings labels. Additionally, this bar has a quite distinctive difference from the rest of Cytyle. To clarify: It looks nothing like the rest of Cydia's labels. pls fix :(

Here's HBANG's repo depictions:
![image](https://cloud.githubusercontent.com/assets/9056756/7193886/6fc48c82-e474-11e4-85ed-0b03c7c7fc02.jpg)

Look how nice this is! There's proper spacing between the Author+CPS labels, and the actual design looks better (kinda). I also appreciate the use of SVG (or PNG?) to indicate the package is supported.

Finally, I'd like to address another general issue with lotus.

You designed the edges of a lotus to edge off, like a square. While this is good for devices like iPads, which unfortunately suffer from cutoff labels in Cydia's iOS 7 CSS, it's actually *noticeably* apparent on iPhone. The actual design philosophy of iOS 7+ is "edge-to-edge". HBANG uses this same edge-to-edge CSS.

I hope you consider this criticism.

Cheers,
Avery Magnotti

**Comment by tmnlsthrn** [comment]
>You designed the edges of a lotus to edge off, like a square. While this is good for devices like iPads, which unfortunately suffer from cutoff labels in Cydia's iOS 7 CSS, it's actually noticeably apparent on iPhone. The actual design philosophy of iOS 7+ is "edge-to-edge". HBANG uses this same edge-to-edge CSS.

Funny fact: these borders should not show up on iPhones (https://github.com/tmnlsthrn/Lotus/blob/master/css/lotus.css#L161L170 & https://github.com/tmnlsthrn/Lotus/blob/master/css/lotus.css#L192L201)

**Comment by tmnlsthrn** [comment]
>You designed the edges of a lotus to edge off, like a square. While this is good for devices like iPads, which unfortunately suffer from cutoff labels in Cydia's iOS 7 CSS, it's actually noticeably apparent on iPhone. The actual design philosophy of iOS 7+ is "edge-to-edge". HBANG uses this same edge-to-edge CSS.

Funny fact: these borders should not show up on iPhones at all
(https://github.com/tmnlsthrn/Lotus/blob/master/css/lotus.css#L161L170 & https://github.com/tmnlsthrn/Lotus/blob/master/css/lotus.css#L192L201)

However, I'll implement a quick fix soon.
